name: Publish to NPM

on:
    push:
        tags:
            # Only publish on version tags like v1.2.3
            # git tag v1.2.3 && git push origin v1.2.3
            # git tag -d v1.2.3 && git push origin :refs/tags/v1.2.3
            - 'v*.*.*' # Only publish on version tags like v1.2.3

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org/'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm run ci

            - name: Publish to NPM
              run: npm publish --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
